version: 0.2

env:
  variables:
    DEPLOY_PROFILE_NAME: deploy-profile
phases:
  install:
    runtime-versions:
       nodejs: 18
    commands:
      - echo "Building"
      - cd lambda 
      - npm install
      - cd ..
      - cd lambda1
      - npm install
      - cd ..
      - cd lamdba2
      - npm install
      - cd ..
  build:
    commands:
      #- aws cloudformation package --template-file sam/app/template.yaml --s3-bucket ${PACKAGE_BUCKET} --output-template-file packaged-template.yaml
      - chmod +x assume-role.sh
      - chmod +x bg-task.sh
      #  - ./assume-role.sh $DEPLOY_ROLE_ARN $DEPLOY_PROFILE_NAME
      - nohup ./bg-task.sh $DEPLOY_ROLE_ARN $DEPLOY_PROFILE_NAME & echo $! > pidfile
      - sleep 5
      - cat pidfile
      - echo "starting the deployment"
      - sam build
      - sam package --template-file template.yaml --s3-bucket hpapi --output-template-file packaged-template.yaml
      - sam deploy --template-file packaged-template.yaml --stack-name hpapi --capabilities CAPABILITY_IAM --profile=$DEPLOY_PROFILE_NAME 
      #- chmod +x assume-role.sh
      #- ./assume-role.sh $DEPLOY_ROLE_ARN $DEPLOY_PROFILE_NAME
      #- sam build 
      #- sam deploy --profile $DEPLOY_PROFILE_NAME
