version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hp-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mpurbcxnkjur"
s3_prefix = "hp-api"
region = "eu-central-1"
profile = "hplab"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
resolve_s3 = true
