AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template
Resources:
 hpapiv1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: index.handler
      Runtime: nodejs18.x

 hpapiv2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda1/
      Handler: index.handler
      Runtime: nodejs18.x